name: CI + CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton plan
        run: echo I am running tecton plan in dev branch
    
  apply-dev:
    if: github.event_name == 'pull_request'
    needs: [plan]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Apply
        run: echo I am running tecton apply in dev branch 
    
#   DeployStaging:
#     name: Deploy to Staging 
#     if: github.event.ref == 'refs/heads/main'
#     needs: [Build]
#     runs-on: ubuntu-latest
#     environment: 
#       name: Staging
#       url: 'http://test.myapp.com'
#     steps:
#       - name: Deploy
#         run: echo I am deploying! 
            
#   DeployProd:
#     name: Deploy to Production 
#     needs: [DeployStaging]
#     runs-on: ubuntu-latest
#     environment: 
#       name: Production
#       url: 'http://www.myapp.com'
#     steps:
#       - name: Deploy
#         run: echo I am deploying! 
    